"""add title version is_active to bots

Revision ID: 71e2094110c3
Revises: 6b654e58d8bb
Create Date: 2026-04-13 13:37:39.911201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e2094110c3'
down_revision: Union[str, Sequence[str], None] = '6b654e58d8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('bots', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('bots', sa.Column('is_active', sa.String(length=10), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'is_active')
    op.drop_column('bots', 'version')
    op.drop_column('bots', 'title')
    # ### end Alembic commands ###
